export const SVC_PROFILE_SUBSCRIPTION_GROUP_NAME =
  'ProfileSubscriptionGroupService';
export const SVC_PROFILE_SUBSCRIPTION_GROUP_WEB_PORT = 3066;
export const SVC_PROFILE_SUBSCRIPTION_GROUP_WEB_ADDRESS =
  process.env.SVC_PROFILE_SUBSCRIPTION_GROUP_WEB_ADDRESS ??
  `http://localhost:${SVC_PROFILE_SUBSCRIPTION_GROUP_WEB_PORT}/graphql`;

export const SVC_PROFILE_SUBSCRIPTION_GROUP_INTERNAL_EVENT_CREATE_ONE =
  'subscriptionGroupCreateOne';
export const SVC_PROFILE_SUBSCRIPTION_GROUP_INTERNAL_EVENT_FIND_ONE =
  'subscriptionGroupFindOne';
export const SVC_PROFILE_SUBSCRIPTION_GROUP_INTERNAL_EVENT_FIND_MANY =
  'subscriptionGroupFindMany';
