export const SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_NAME =
  'ProfileSubscriptionGroupMembershipService';
export const SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WEB_PORT = 3068;
export const SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WEB_ADDRESS =
  process.env.SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WEB_ADDRESS ??
  `http://localhost:${SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WEB_PORT}/graphql`;

// Events
export const INTERNAL_EVENT_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_CREATE_ONE =
  'subscriptionGroupMembershipCreateOne';
export const INTERNAL_EVENT_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_FIND_ONE =
  'subscriptionGroupMembershipFindOne';
export const INTERNAL_EVENT_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_FIND_MANY =
  'subscriptionGroupMembershipFindMany';
export const INTERNAL_EVENT_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_DELETE_ONE =
  'subscriptionGroupMembershipDeleteOne';

// Messages
export const INTERNAL_MESSAGE_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WAS_CREATED =
  'INTERNAL_MESSAGE_SVC_PROFILE_SUBSCRIPTION_GROUP_MEMBERSHIP_WAS_CREATED';
