export const SESSION_SERVICE_NAME = 'SessionService';
export const SESSION_SERVICE_WEB_SERVER_PORT = 3004;
export const SESSION_SERVICE_MICROSERVICE_PORT = 4222;
export const SESSION_SERVICE_WEB_SERVER_ADDRESS =
  process.env.SESSION_SERVICE_WEB_SERVER_ADDRESS ??
  `https://localhost:${SESSION_SERVICE_WEB_SERVER_PORT}/graphql`;
export const SESSION_SERVICE_MICROSERVICE_HOST =
  process.env.SESSION_SERVICE_MICROSERVICE_HOST ?? 'localhost';

export const SESSION_SERVICE_INTERNAL_EVENT_FIND_ONE_BY_ID =
  'sessionFindOneByID';
