export const SVC_PAYMENT_RECURRING_INVOICE_NAME =
  'PaymentRecurringInvoiceService';
export const SVC_PAYMENT_RECURRING_INVOICE_WEB_PORT = 3048;
export const SVC_PAYMENT_RECURRING_INVOICE_WEB_ADDRESS =
  process.env.SVC_PAYMENT_RECURRING_INVOICE_WEB_ADDRESS ??
  `http://localhost:${SVC_PAYMENT_RECURRING_INVOICE_WEB_PORT}/graphql`;

export const SVC_PAYMENT_RECURRING_INVOICE_INTERNAL_EVENT_FIND_ONE =
  'messageFindOneByID';
