export enum ErrorCode {
  ResourceAccessDenied = 1,
  UserWireMissingRoleRelation = 100,
  UserCreationUsernameIsTaken = 200,
  UserCreationEmailIsTaken = 201,
  UserDoesNotExist = 202,
  SessionLoginUserDoesNotExist = 300,
  SessionLoginAuthenticationError = 301,
  ProfileDoesNotExist = 401,
  MediaDoesNotExist = 700,
  MediaInvalidFileType = 701,
  PostWireReceivedWrongType = 801,
  PostWireMissingMedia = 802,
  PostWireMissingQuizChoices = 803,
  PostWireMissingPollChoices = 804,
  PostWrongType = 805,
  PostDoesNotExist = 806,
  PostWrongMediaType = 807,
  PostInvalidType = 808,
  PostWireMissingQuizReactions = 810,
  PostWireMissingPollReactions = 811,
  PostChoiceReactionHasInvalidChoiceSelected = 812,
  PostChoiceReactionDoesNotExist = 813,
  PostCannotHaveReactions = 814,
  PostChoiceWithIndicatorMissingCorrectField = 815,
}
