export const PROFILE_SERVICE_NAME = 'ProfileService';
export const PROFILE_SERVICE_WEB_SERVER_PORT = 3008;
export const PROFILE_SERVICE_MICROSERVICE_PORT = 4222;
export const PROFILE_SERVICE_WEB_SERVER_ADDRESS =
  process.env.PROFILE_SERVICE_WEB_SERVER_ADDRESS ??
  `https://localhost:${PROFILE_SERVICE_WEB_SERVER_PORT}/graphql`;
export const PROFILE_SERVICE_MICROSERVICE_HOST =
  process.env.PROFILE_SERVICE_MICROSERVICE_HOST ?? 'localhost';

export const PROFILE_SERVICE_INTERNAL_EVENT_FIND_ONE_BY_ID =
  'profileFindOneByID';
